# Версия 1.0 (2025-06-15)
# Тест порта 22: GitHub Actions → твой сервер

name: Debug Port 22 SSH Access

on:
  workflow_dispatch:

jobs:
  trace-and-curl:
    runs-on: ubuntu-latest

    steps:
    - name: Curl port 22
      run: |
        echo ">>> CURL TEST (TCP/22)"
        curl -v telnet://185.144.159.117:22 || echo "Curl failed"

    - name: Traceroute to server
      run: |
        echo ">>> TRACEROUTE"
        sudo apt-get update && sudo apt-get install -y traceroute
        traceroute 185.144.159.117

    - name: Show runner IP
      run: |
        echo ">>> GitHub runner public IP:"
        curl https://ipinfo.io/ip
