name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_USER }}
        key: ${{ secrets.PROD_KEY }}
        port: 2222
        script: |
          echo ">>> Debug: SSH PORT is set to 2222"
          echo ">>> Host: ${{ secrets.PROD_HOST }}"
          echo ">>> Username: ${{ secrets.PROD_USER }}"
          cd /var/www/aianswerline
          git pull origin master
