# Версия 1.1 (2025-06-15)
# DIANA: Проверка доступа GitHub Runner к порту 22 + лог IP и даты

name: DIANA: Test SSH Port Access

on:
  workflow_dispatch:

jobs:
  test-ssh-port:
    runs-on: ubuntu-latest

    steps:
      - name: Print date and runner IP
        run: |
          echo "🕒 Дата запуска: $(date)"
          echo "🌐 IP GitHub Runner:"
          curl -s https://ipinfo.io/ip

      - name: Test TCP port 22 to target
        run: |
          echo "🚀 Проверка соединения с сервером ${{ secrets.PROD_HOST }} на порт 22..."
          timeout 5 bash -c "</dev/tcp/${{ secrets.PROD_HOST }}/22" && echo "✅ Порт 22 открыт" || echo "❌ Порт 22 закрыт или недоступен"
