# Версия 1.1 (2025-06-15)
# DIANA: Network Debugging — full trace

name: DIANA: Full Debug Trace

on:
  workflow_dispatch:

jobs:
  netcheck:
    runs-on: ubuntu-latest
    steps:
      - name: DNS resolution
        run: |
          echo "[DNS] github.com:"
          nslookup github.com
      - name: Outbound curl to GitHub
        run: |
          echo "[CURL] github.com:22"
          curl -v telnet://github.com:22 || true
      - name: Outbound curl to google.com
        run: |
          echo "[CURL] google.com"
          curl -s https://google.com || echo "FAILED"
