# Версия 1.0 (2025-06-15)
# Проверка доступа GitHub Runner к SSH-порту сервера

name: DIANA: Test SSH Port Access

on:
  workflow_dispatch:

jobs:
  test-ssh-port:
    runs-on: ubuntu-latest
    steps:
      - name: Test TCP port 22 to ${{ secrets.PROD_HOST }}
        run: |
          echo ">> Проверка подключения к ${{ secrets.PROD_HOST }}:22"
          timeout 5 bash -c "</dev/tcp/${{ secrets.PROD_HOST }}/22" \
            && echo '✅ Порт 22 открыт' \
            || echo '❌ Порт 22 закрыт или недоступен'
