# Версия 1.0 (2025-06-15)
# Reveal GitHub Actions runner IP and trace SSH connectivity

name: DIANA: Reveal runner IP

on:
  workflow_dispatch:

jobs:
  reveal-ip:
    runs-on: ubuntu-latest

    steps:
    - name: Reveal runner public IP
      run: |
        echo "=== GitHub Actions Runner IP ==="
        curl https://ifconfig.me
        echo ""
        echo "=== DNS name of your server ==="
        nslookup ${{ secrets.PROD_HOST }}

    - name: Traceroute to your server
      run: |
        sudo apt-get update
        sudo apt-get install -y traceroute
        echo "=== Traceroute to ${{ secrets.PROD_HOST }} ==="
        traceroute -n ${{ secrets.PROD_HOST }}

    - name: Curl SSH port check
      run: |
        echo "=== Curl check to SSH port 22 ==="
        curl -v telnet://${{ secrets.PROD_HOST }}:22 --connect-timeout 10 || echo "Curl timed out (expected if blocked)"
